openapi: 3.0.3
info:
  title: Common API Conventions
  version: 0.1.0
components:
  responses:
    Problem:
      description: RFC7807 Problem Details
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type: { type: string, format: uri }
              title: { type: string }
              status: { type: integer }
              detail: { type: string }
              instance: { type: string }
