spring:
  application:
    name: household-budget

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:hb}
    username: ${POSTGRES_USER:hbuser}
    password: ${POSTGRES_PASSWORD:hbpass}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jooq:
    sql-dialect: POSTGRES

server:
  port: ${APP_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[com.raccoon.householdbudget]": DEBUG
