spring:
  application:
    name: household-budget

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false  # H2 인메모리 DB에서는 Flyway 비활성화

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  jooq:
    sql-dialect: H2

server:
  port: ${APP_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[org.springframework.web]": DEBUG
    "[com.raccoon.householdbudget]": DEBUG
