repos:
  - repo: https://github.com/diffplug/spotless
    rev: v2.43.0
    hooks:
      - id: spotless-maven
        name: spotless-apply
        entry: mvn spotless:apply
        language: system
        pass_filenames: false

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
